### ISSUE TITLE
Accessing results file as artifact

### ISSUE THREAD

**Issue by SuperKogito** [urlstechie/urlchecker-action#51]
Thanks, very cool! My plan is to write a workflow uploading the csv as artifact. :-)

_Originally posted by @maelle in https://github.com/urlstechie/urlchecker-python/issues/24#issuecomment-612742661_

I'm trying to write a workflow uploading the artifact and have a question. I tried various things and might be missing something obvious regarding paths.

[Workflow](https://github.com/r-hub/docs/blob/gha/.github/workflows/urlchecks.yml)

https://github.com/r-hub/docs/runs/582541285?check_suite_focus=true

* The URL-checks actions is "Saving results to /github/workspace/output/urls.csv"
* But then the upload-artifact function tries to find it in "/home/runner/work/docs/docs/output"

Do you have any tip regarding where it might be best to tweak things?

No worries if you don't answer, I'm not sure this is the right place to ask. :-)

**Comment by SuperKogito** [comment]
@SuperKogito
Member
SuperKogito commented 1 hour ago •

This might be what you are looking for, the description fits the use-case but tbh I am not sure how exactly to do the mentioned chmod step. Maybe this can give you a hint, https://github.community/t5/GitHub-Actions/Access-to-path-denied-during-artifact-upload/td-p/33562
This also seems similar, https://gitlab.com/gitlab-org/gitlab-runner/issues/2082. Maybe you can try something like - docker `cp $DOCKER_IMAGE_BUILD_TAG_ID:/bqis-backend/target/junitxmlreport $CI_PROJECT_DIR/junitreport` as @mmayerhofer suggested in his answer.

----

@maelle
Author
maelle commented 1 hour ago

Thanks! Does the action run in a container? I also saw https://help.github.com/en/actions/reference/virtual-environments-for-github-hosted-runners#docker-container-filesystem

-------
@maelle
Author
maelle commented 1 hour ago

I suppose my question is, should I tweak my workflow (perfectly fine) or should the action save the CSV in a place that'd be directly accessible by upload-artifact?

----

@SuperKogito
Member
SuperKogito commented 8 minutes ago

Technically the action is just a Docker, that uses the python package and we just access it using an entrypoint.
Your workflow looks okay to me, but that's a very good question and a fair point, that we should discuss with @vsoch.

----

@maelle
Author
maelle commented 5 minutes ago

I'll wait before tweaking any further, then.

My idea was that if the workflow fails, it might be good to look over URLs in some sort of spreadsheets to keep track of fixes/notes, hence my wanting the artifact. And if it doesn't fail the artifact might be fun too (e.g. looking at most frequent domains or so), but less crucial.

**Comment by vsoch** [comment]
@SuperKogito it's work to just use a relative path, the troubles you are listing are just related to general difficulty with using GitHub workspace vs. clone directory. See https://github.com/urlstechie/urlchecker-action/blob/master/.github/workflows/main.yml#L22 for how simple this is to do.

**Comment by vsoch** [comment]
I don't think this is a bug with the library - can you please explain why you opened an issue?

**Comment by maelle** [comment]
Because I couldn't find the right combination of path options for your library and the upload-artifacts action to cooperate.

**Comment by vsoch** [comment]
The library is agnostic to the paths that you choose - if you save a relative path it is relative to the GitHub working directory that is bound to the container, which should be the same for subsequent actions. I opened a PR with an example to add but the actions for the repo didn't trigger - now I'm wondering if there is some issue with actions period!

**Comment by vsoch** [comment]
okay I reset the actions settings in the repo and pushed again, that seemed to fix it! I also had no issue uploading the file, see below:

![image](https://user-images.githubusercontent.com/814322/79134308-bb43a780-7d6a-11ea-960a-a84f7b3a37b7.png)

and the artifact

![image](https://user-images.githubusercontent.com/814322/79134673-52a8fa80-7d6b-11ea-95e2-1b6a01a53ffa.png)

**Comment by vsoch** [comment]
And here is the yaml recipe:

```yaml
    - name: Test UrlChecker Action with Save
      uses: urlstechie/urlchecker-action@0.1.9
      with: 
        git_path: https://github.com/urlstechie/urlchecker-test-repo
        subfolder: test_action
        file_types: .md
        force_pass: true
        save: "results.csv"
    - name: Check that results exist
      run: cat results.csv
    - name: Upload check results
      if: success()
      uses: actions/upload-artifact@v1
      with:
        name: urlchecker-results
        path: results.csv
```

**Comment by vsoch** [comment]
@maelle you have a path error in your recipe - `/output` != `output`. You have:

```yaml
    - name: URLs-checker
      uses: urlstechie/urlchecker-action@0.1.9
      with:
        # A comma-separated list of file types to cover in the URL checks
        file_types: .md
        save: output/urls.csv
    
    - name: Archive URL checking results
      if: always()
      uses: actions/upload-artifact@v2-preview
      with:
        name: urls
        path: /output/urls.csv
```
But you need to have:

```yaml
    - name: URLs-checker
      uses: urlstechie/urlchecker-action@0.1.9
      with:
        # A comma-separated list of file types to cover in the URL checks
        file_types: .md
        save: output/urls.csv
    
    - name: Archive URL checking results
      if: always()
      uses: actions/upload-artifact@v2-preview
      with:
        name: urls
        path: output/urls.csv
```
I don't think there is an issue here so I'm closing, but please reopen if I'm mistaken.
