### ISSUE TITLE
dependabot is trying to update from 0.0.27 to 0.2.31 after version scheme change

### ISSUE THREAD

**Issue by lucasrangit** [urlstechie/urlchecker-action#88]
Take a look at https://github.com/berlin-hack-and-tell/berlinhackandtell.rocks/pull/320 and you'll see @dependabot tying to merge the update from 0.0.27 to 0.2.31. 

It is confused by the version scheme change. 

Since you cannot remove "old" version, I suggest changing the version scheme again. Since you want to match URLchecker, then you should use major.minor versions only. e.g. 0.0.27 becomes 0.27. 

That will fix the issue since 0.27 > 0.2.31 > 0.0.27.

**Comment by vsoch** [comment]
Can you not just ignore the suggested update?

**Comment by lucasrangit** [comment]
Yeah we can ignore it. I also think there's a way to configure the @dependabot to ignore some versions with `.github/dependabot.yml` so I don't have to disable auto-update completely.

```yaml
- version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "urlchecker-action"
        # Ignore old version scheme
        versions: ["0.2.x", "0.1.x"]
```

I am reporting this because you made the change to make our lives easier :wink:

![image](https://user-images.githubusercontent.com/701818/171639876-d0fc1c88-02e2-4898-8613-c2df28548737.png)
